require("julien.packer")
require("julien.core.options")
require("julien.core.keymaps")
require("julien.core.colorscheme")

require("julien.plugins.comment")
require("julien.plugins.nvim-tree")
require("julien.plugins.lualine")
require("julien.plugins.telescope")
require("julien.plugins.nvim-cmp")
require("julien.plugins.autopairs")
require("julien.plugins.treesitter")
require("julien.plugins.gitsigns")
require("julien.plugins.colorizer")
require("julien.plugins.harpoon")

require("julien.plugins.lsp.mason")
require("julien.plugins.lsp.lspsaga")
require("julien.plugins.lsp.lspconfig")
require("julien.plugins.lsp.null-ls")
